version: "3.8"
services:
  db:
    container_name: mysqldb
    image: mysql:8.0.27
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_USER: sa
      MYSQL_PASSWORD: mysql123
      MYSQL_DATABASE: db_produtos
    ports:
      - "3306:3306"